### ISSUE TITLE
rspec tests installing puppet 4

### ISSUE THREAD

**Issue by pelacables** [arioch/puppet-ocsinventory#1]
Hi,

I wanted to contribute to this module and I've added support for SL6 (RH6). 
My problem is that the bundle installs latest version of puppet (4) facter and hiera and if I try to for it to use my puppet/facter/hiera/version it fails:

$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using CFPropertyList 2.2.8
Using diff-lcs 1.2.5
Installing facter 2.4.3
Using json_pure 1.8.2
Installing hiera 1.3.4 (was 2.0.0)
Using metaclass 0.0.4
Using mocha 1.1.0
Installing puppet 3.7.5 (was 4.0.0)
Using puppet-lint 1.1.0
Using puppet-syntax 2.0.0
Using rspec-support 3.2.2
Using rspec-core 3.2.3
Using rspec-expectations 3.2.1
Using rspec-mocks 3.2.1
Using rspec 3.2.0
Using rspec-puppet 2.1.0 from https://github.com/rodjek/rspec-puppet.git (at master)
Using puppetlabs_spec_helper 0.10.2
Using bundler 1.9.2
Bundle complete! 8 Gemfile dependencies, 19 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

I guess I must use some other old version of several rspec\* gems. 
Could you please show me the proper version of those gems?

Cheers,
Arnau

**Comment by arioch** [comment]
That should be fixed now (a63cc3ea7e3fd5b4a627bdd88b8aec1633fd87c9).
Could you please try again?

```
bundle
bundle update
bundle exec rake spec
```

**Comment by pelacables** [comment]
Hi,

still using 4 and should be 3.7.(5).  Same for hiera, it install 2.0.0 and I'm running 1.3.4...

$ bundle 
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Installing rake 10.4.2
Installing CFPropertyList 2.2.8
Installing diff-lcs 1.2.5
Installing facter 2.4.3
Installing json_pure 1.8.2
Installing hiera 2.0.0
Installing metaclass 0.0.4
Installing mocha 1.1.0
Installing puppet 4.0.0
[...]

that >= 3.7.4 allows puppet 4 to be installed.

*If you want I can create the pull request without running the test. the change is really simple.

Cheers,
Arnau

**Comment by arioch** [comment]
```
PUPPET_VERSION=3.7.5 FACTER_VERSION=2.2.0 bundle; bundle update; bundle exec rake spec
```

**Comment by arioch** [comment]
Go ahead and send in your pull request.
I'll check what's going on if the build fails.

**Comment by arioch** [comment]
This ticket has become redundant by https://github.com/arioch/puppet-ocsinventory/pull/3.
Closing.
